In [1]:

# 이상치 dict 읽는 코드

def check_speed(df):
    # 이상치 vs df 분포 체크
    # if slow : feedback_speed(slow)
    # elif fast : feedback_speed(fast)
    
def feedback_speed(speed):
    # if speed is slow:
    #     print("")
    # else print("")

IndentationError: expected an indented block (<ipython-input-1-1ea174fe267f>, line 8)

In [16]:
import pandas as pd
trainer_pose = pd.read_csv('../data/output_left.csv', header=None)
trainer_pose.describe(include="all")

0            1            2            3            4   \
count  1209.000000  1209.000000  1209.000000  1209.000000  1209.000000   
mean      0.033912   217.383788   100.789082   198.367246   130.147229   
std       0.181078     3.808530    20.996279     3.498456    22.740288   
min       0.000000   211.000000    70.000000   192.000000   102.000000   
25%       0.000000   213.000000    79.000000   195.000000   106.000000   
50%       0.000000   218.000000    96.000000   198.000000   128.000000   
75%       0.000000   220.000000   122.000000   202.000000   153.000000   
max       1.000000   226.000000   139.000000   205.000000   172.000000   

                5            6            7            8            9   ...  \
count  1209.000000  1209.000000  1209.000000  1209.000000  1209.000000  ...   
mean    196.551696   129.941274   183.932175   166.828784   198.709677  ...   
std       3.566657    23.208400    10.782637    27.825342    13.864562  ...   
min     191.000000   102.000000   170.000000   115.000000   188.000000  ...   
25%     193.000000   106.000000   176.000000   140.000000   192.000000  ...   
50%     196.000000   127.000000   180.000000   163.000000   193.000000  ...   
75%     200.000000   152.000000   185.000000   192.000000   196.000000  ...   
max     204.000000   174.000000   221.000000   226.000000   249.000000  ...   

                27           28           29           30           31  \
count  1209.000000  1209.000000  1209.000000  1209.000000  1209.000000   
mean    239.676592   363.976840   213.893300    94.428453    23.727047   
std       2.469776     2.069838     3.846306    21.307393    67.815414   
min     183.000000   325.000000   205.000000    67.000000     0.000000   
25%     239.000000   364.000000   211.000000    75.000000     0.000000   
50%     240.000000   364.000000   214.000000    93.000000     0.000000   
75%     240.000000   365.000000   216.000000   115.000000     0.000000   
max     242.000000   366.000000   222.000000   131.000000   222.000000   

                32           33           34      35      36  
count  1209.000000  1209.000000  1209.000000  1209.0  1209.0  
mean     10.339123   201.894955    96.056245     0.0     0.0  
std      30.435756     4.324355    21.948506     0.0     0.0  
min       0.000000   193.000000    68.000000     0.0     0.0  
25%       0.000000   198.000000    75.000000     0.0     0.0  
50%       0.000000   202.000000    93.000000     0.0     0.0  
75%       0.000000   204.000000   119.000000     0.0     0.0  
max     130.000000   213.000000   133.000000     0.0     0.0  

[8 rows x 37 columns]

In [15]:
import pandas as pd
trainer_pose = pd.read_csv('../data/eigen_value.csv', header=None).iloc[0,:]
trainer_pose.values

array([ 1.59742096e-02,  4.01878126e-01,  9.90766020e-03,  4.34488468e-01,
        3.03097284e-02,  4.19651693e-01,  1.22450512e-01, -2.55182371e-03,
        1.91034822e-02,  1.23883774e-02, -9.05468020e-05,  4.47154157e-01,
        7.98219022e-03,  5.06728415e-01, -4.40782692e-03, -3.38351130e-03])

In [13]:
from sklearn.decomposition import PCA

trainer_pose = pd.read_csv('../data/output_right.csv', header=None)
pca_df = trainer_pose.loc[:,[1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]

pca_df = pca_df.replace(0, np.nan)
pca_df = pca_df.dropna()
pca_df.describe()
pca = PCA(n_components=1)
pca.fit(pca_df)
re_vector = pca.components_[0]

trainer_pose = trainer_pose.loc[:,[0,1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]
print(trainer_pose.iloc[0,1:].values)
df = pd.read_csv('../data/output_left.csv', header=None)
df = df.loc[:,[1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]

def check_speed(my_pose, tr_pose, pca):
    # trainer pose vs my pose 분포 비교
    my_pose = my_pose.values
    tr_pose = tr_pose.values
    my_dist = pca.fit_transform(my_pose)
    tr_dist = pca.fit_transform(tr_pose)

check_speed(df.iloc[[i for i in range(35)],:], trainer_pose.iloc[[i for i in range(35)],1:])




[231  84 211 113 210 210 241 275 252 366 206 209 185 286 145 338]


TypeError: check_speed() missing 1 required positional argument: 'pca'

In [8]:
import pandas as pd
import numpy as np
list_p_df = pd.read_csv('../data/output_right.csv', header=None)
list_p_df = list_p_df.loc[:,[1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]
list_p_df = list_p_df.iloc[[i for i in range(35)],:]
list_p_df.replace(0,np.nan).fillna(method="ffill")




     1    2    3    4    17   18   19   20   21   22   23   24   25   26  \
0   231   84  211  113  210  210  241  275  252  366  206  209  185  286   
1   231   84  213  113  211  211  241  276  252  366  208  210  185  286   
2   231   84  213  113  211  211  241  276  252  366  207  210  185  286   
3   231   85  213  113  211  211  241  276  252  366  207  210  185  287   
4   231   84  213  113  210  213  241  275  252  366  206  211  184  291   
5   231   84  213  113  210  213  241  275  252  366  206  211  184  292   
6   231   86  213  114  211  214  241  275  252  366  208  213  184  293   
7   231   85  213  115  210  215  242  276  252  366  206  213  184  294   
8   231   85  213  116  210  216  242  275  252  366  206  214  185  294   
9   231   87  213  118  210  218  242  275  252  366  205  217  185  296   
10  231   89  213  120  209  220  244  275  252  366  204  219  184  301   
11  231   89  213  121  211  219  244  275  252  366  207  217  184  302   
12  232   94

In [19]:
from sklearn.decomposition import PCA

trainer_pose = pd.read_csv('../data/output_right.csv', header=None)
pca_df = trainer_pose.loc[:,[1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]

pca_df = pca_df.replace(0, np.nan)
pca_df = pca_df.dropna()
pca_df.describe()
pca = PCA(n_components=1)
pca.fit(pca_df)
re_vector = pca.components_[0]

trainer_pose = trainer_pose.loc[:,[0,1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28]]
trainer_pose=trainer_pose.iloc[0,1:].values

people_pose = {0: (280, 58), 1: (299, 96), 2: (287, 96), 3: (277, 134), 4: (268, 117), 5: (311, 93), 6: (359, 123), 7: (303, 139), 8: (303, 166), 9: (330, 224), 11: (312, 166), 12: (263, 213), 13: (279, 276), 14: (280, 58), 15: (287, 59), 17: (301, 60)}
people_pose = np.array([p for p in people_pose.values()]).flatten() # dict-tuple -> list
people_pose = people_pose[[0,1,2,3,16,17,18,19,20,21,22,23,24,25,26,27]]

mse = ((people_pose - trainer_pose)**2).mean(axis = 0)
print(mse)


[231  84 211 113 210 210 241 275 252 366 206 209 185 286 145 338] [280  58 299  96 303 166 330 224 312 166 263 213 279 276 280  58]
11540.1875


In [26]:
pose_dict={0: (280, 58), 1: (299, 96), 2: (287, 96), 3: (277, 134), 4: (268, 117), 5: (311, 93), 6: (359, 123), 7: (303, 139), 8: (303, 166), 9: (330, 224), 11: (312, 166), 12: (263, 213), 13: (279, 276), 14: (280, 58), 15: (287, 59), 17: (301, 60)}

l_li=[i for i in range(18) if i not in list(pose_dict.keys())]
for l_item in l_li:
    pose_dict[l_item] = (0,0)

print(l_li)
print(pose_dict)

[10, 16]
[10, 16]
{0: (280, 58), 1: (299, 96), 2: (287, 96), 3: (277, 134), 4: (268, 117), 5: (311, 93), 6: (359, 123), 7: (303, 139), 8: (303, 166), 9: (330, 224), 11: (312, 166), 12: (263, 213), 13: (279, 276), 14: (280, 58), 15: (287, 59), 17: (301, 60), 10: (0, 0), 16: (0, 0)}
